### ISSUE TITLE
Ability to cancel lambdas

### ISSUE THREAD

**Issue by error454** [getnamo/ZipUtility-ue4#18]
I have started to look into the minimum viable changes to be able to cancel in-flight unzip operations. I'm generally a little confused so wanted to ask for some advice.

In `WFULambdaRunnable`, I see` FThreadSafeBool Finished`. This is set to true/false in a few places to track the state of the runnable but is never actually polled anywhere that I can find. I was reading the comments in https://github.com/getnamo/ZipUtility-ue4/issues/11, which makes it sound like the ability to cancel early was on the TODO list.

My other point of confusion is that the 7zip library extraction routines are a single call, they're not called in some looped Runnable where bailing out early via flag is an option. So it seems to me that the only way to actually cancel a started zip operation is to pull the rug out from under it and kill the thread entirely.

Digging a little into the 7z library, I found [this question](https://sourceforge.net/p/sevenzip/discussion/45798/thread/c9697dfd/) which seems to indicate the use of `CheckBreak()`. I need to spend more time in the 7z library code to understand how this works. I feel this is probably the best path to shake out first. I wanted to see if you had any ideas for cleanly killing an in-flight zip operation that might guide me down a better path... if I have to dip into the 7z plugin side I may also investigate adding password support and in-memory extraction while I'm there.

**Comment by getnamo** [comment]
Igor Pavlov is the creator of 7zip so I'd take his word for how to get the stop call working. 

Looking through the 7zip++ code, ```CheckBreak()``` is define here: https://github.com/keithjjones/7z/blob/174a5af5960d2bbebc7deb3b7bc622f5f62b9a3e/CPP/7zip/UI/Common/UpdateCallback.h#L23 and based on that I'd suspect the best place to add the function would be inside https://github.com/getnamo/7zip-cpp/blob/master/7zpp/ArchiveExtractCallback.h#L18, where we would possibly add/replace our callback inheritance to use [IUpdateCallbackUI](https://github.com/keithjjones/7z/blob/174a5af5960d2bbebc7deb3b7bc622f5f62b9a3e/CPP/7zip/UI/Common/UpdateCallback.h#L38) which would include the checkbreak function. You'd probably want to balance that by adding it inside https://github.com/getnamo/7zip-cpp/blob/master/7zpp/ArchiveUpdateCallback.h#L17 too.

From there it's a matter of linking this up to our own callback system defined here: https://github.com/getnamo/7zip-cpp/blob/master/7zpp/ProgressCallback.h which is linked inside https://github.com/getnamo/ZipUtility-ue4/blob/master/Source/ZipUtility/Private/ZipFileFunctionLibrary.cpp#L35. 

It's been a while since I've familiarized myself with this repo, but that should be the major pieces to get this enhancement working. The other issue thread was mainly talking about being able to stop lambda threads, but I imagine this will be important to linkup the ability to cancel extraction/compression in flight from lambda definitions.

Pop a pull request when you have something working and I'll merge it to master on both repositories.

**Comment by getnamo** [comment]
Merged in https://github.com/getnamo/ZipUtility-ue4/commit/bb0fefedacfa2e204b8b3d6694fa41fa0e709ea9 and https://github.com/getnamo/ZipUtility-ue4/commit/f4a6ee9d25f946939e34c0f9c1c5fcbe46e6bb48
